# Generated by Django 2.0.3 on 2018-08-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDEA_Interactive', '0002_auto_20180821_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelautosna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default=True, max_length=5),
        ),
    ]
