# Generated by Django 2.0.3 on 2018-08-21 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDEA_Interactive', '0005_auto_20180821_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelautosna',
            name='node_num',
            field=models.IntegerField(choices=[(35, 'Small'), (60, 'Regular'), (100, 'Large')], default=35, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelautowc',
            name='page_range',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='node_num',
            field=models.IntegerField(choices=[(35, 'Small'), (60, 'Regular'), (100, 'Large')], default=35, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=5),
        ),
    ]
