# Generated by Django 2.0.3 on 2018-08-21 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDEA_Simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelautosna',
            name='fa2_1',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='modelautosna',
            name='fa2_2',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='modelautosna',
            name='fa2_iter',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='modelautosna',
            name='fr_iter',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='modelautosna',
            name='fr_k',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='modelautosna',
            name='layout',
            field=models.CharField(choices=[('FR', 'Fruchterman Reingold'), ('FA2', 'ForceAtlas2')], default='FR', max_length=25),
        ),
        migrations.AddField(
            model_name='modelautosna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default=True, max_length=5),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='fa2_1',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='fa2_2',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='fa2_iter',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='fr_iter',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='fr_k',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='layout',
            field=models.CharField(choices=[('FR', 'Fruchterman Reingold'), ('FA2', 'ForceAtlas2')], default='FR', max_length=25),
        ),
        migrations.AddField(
            model_name='modelsna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='modelautosna',
            name='edge_remove_threshold',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelautosna',
            name='node_num',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelautosna',
            name='page_range',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelautosna',
            name='stop_words',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='edge_remove_threshold',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='node_num',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='stop_words',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
