# Generated by Django 2.0.3 on 2018-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDEA_Simple', '0002_auto_20180821_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelautosna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=5),
        ),
        migrations.AlterField(
            model_name='modelsna',
            name='remove_isolated_node',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=5),
        ),
    ]
